### ISSUE TITLE
How to use this with Docker-Compose

### ISSUE THREAD

**Issue by techcubs** [aexel90/hue_exporter#1]
I am struggling to figure out how to compile this so that i can use this with docker compose (by placing it in docker-compose.yml) and also create a job in prometheus.yml.

**Comment by dj95** [comment]
Hi @techcubs ,

I'm not sure if this is still an issue for you, but here's a small config for Docker and docker-compose, that works for me.

**Dockerfile**

```Dockerfile
#
# Step 1 - Build the binary
#

# use the latest go image for building the exporter
FROM golang AS builder

# build arguments in order to reuse it for arm containers (e.g. for a RPi)
ARG GOOS=linux
ARG GOARCH=amd64
ARG GOARM

# disable go modules
ENV GO111MODULE="off"

# download and build the binary. The binary must compile all dependencies
# into one binary in order to use it within a scratch image
RUN go get github.com/aexel90/hue_exporter/ \
 && cd $GOPATH/src/github.com/aexel90/hue_exporter \
 && CGO_ENABLED=0 GOOS="${GOOS}" GOARCH="${GOARCH}" GOARM="${GOARM}" go build \
    -ldflags="-s -w" \
    -a \
    -installsuffix cgo \
    -o /go/bin/hue_exporter \
    ./main.go


#
# Step 2 - Download ca-certificates
#

# use a small distro to obtain the current ca certificates
FROM alpine as ca-certificates

# install the certificates with apk
RUN apk add --no-cache \
        ca-certificates


#
# Step 3 - Package the runtime image
#

# start with an empty image
FROM scratch

# copy the binary from the builder
COPY --from=builder /go/bin/hue_exporter /hue_exporter

# copy the ca certificates from step 2
COPY --from=ca-certificates /etc/ssl /etc/ssl

# copy the metrics file from the project folder
COPY --from=builder /go/src/github.com/aexel90/hue_exporter/hue_metrics.json /hue_metrics.json

# expose the default port
EXPOSE 9773

# use the built binary as entrypoint
ENTRYPOINT ["/hue_exporter"]
```

**docker-compose.yaml**

```yaml
version: '3.5'
services:
  hue_exporter:
    build:
      context: '.'
      dockerfile: 'Dockerfile'
      args:
        GOOS: 'linux'
        GOARCH: 'amd64'
        GOARM: ''
    command:
    - '-hue-url=10.10.10.50'
    - '-username=REDACTED'
    - '-metrics-file=/hue_metrics.json'
    - '-listen-address=0.0.0.0:9773'
    image: 'hueexporter:dev'
    network_mode: 'host'
```

After you've started the container, metrics should be available on the host, on which you've started the container (e.g. if your docker host has the IP address `10.10.10.10` metrics are available at `http://10.10.10.10:9773/metrics`).

The scrape config in prometheus should contain the following config:

```yaml
- job_name: hue
  scrape_interval: 15s
  static_configs:
  - targets:
    - 10.10.10.10:9773
```
